#!/bin/bash
# @TODO: DOCUMENT THIS CHANGE
# Merge the dev branch to your working branch

# in the working branch
git checkout dev-jade
git pull
git add .
git commit -a -m "preparing to merge from dev"
git push

# In the dev branch
git checkout dev
git pull

# in the working branch
git checkout dev-jade
git merge dev
git add .
git commit -a -m "merging updates from dev"
git push
