#!/bin/bash
# Merge the dev branch to your working branch

read -r -p "Enter the name of your working branch: " devBranch 

# in the working branch
git checkout $devBranch
git pull
git add .
git commit -a -m "preparing to merge from dev"
git push

# In the dev branch
git checkout dev
git pull

# in the working branch
git checkout $devBranch
git merge dev
git add .
git commit -a -m "merging updates from dev"
git push
