#!/bin/bash

npm i
npm update

mv .gitignore temp.gitignore

git submodule add https://github.com/jauntyjocularjay/kwikgit.git git
git submodule add https://github.com/jauntyjocularjay/jsutils.git src/module/jsutils
git submodule add https://github.com/jauntyjocularjay/chaitests.git src/module/chaitests

mv temp.gitignore .gitignore
