#!/bin/bash
# Dev-start is run after setup and cloning.

npm i
npm update

mv .gitignore temp.gitignore

git submodule add https://github.com/jauntyjocularjay/kwikgit.git git
git submodule add https://github.com/jauntyjocularjay/jsutils.git public/module/jsutils
git submodule add https://github.com/jauntyjocularjay/chaitests.git public/module/chaitests

mv temp.gitignore .gitignore

echo "git/" >> .gitignore
echo "jsutils/" >> .gitignore
echo "chaitests/" >> .gitignore
