#!/bin/bash

git stash

git fetch --all 

read -r -p "Enter your dev branch name to update or press ctrl+c to exit: " devBranch
git merge $devBranch dev

git checkout $devBranch
git pull

echo "Done, you are now on $devBranch."

