#!/bin/bash

# echo "What is the name of the application?"
# read name

# echo "Setting up express with Pug and standard CSS"

# npx express-generator --git --pug $name

# cd $name

mv .gitignore temp.gitignore

git submodule add https://github.com/jauntyjocularjay/kwikgit.git git
git submodule add https://github.com/jauntyjocularjay/jsutils.git public/module/jsutils
git submodule add https://github.com/jauntyjocularjay/chaitests.git public/module/chaitests

mv temp.gitignore .gitignore

echo "node_modules/" >> .gitignore
echo "git/" >> .gitignore
echo "jsutil/" >> .gitignore
echo "chaitests/" >> .gitignore

npm install nodemon --save-dev
npm install express --save-dev
npm i

DEBUG=myapp:* npm start

